"""Makefile generator for ncnn backend models."""
from pathlib import Path


def generate_makefile(output_dir: Path, model_name: str, debug: dict | None = None, **kwargs) -> Path:
    debug = debug or {}
    extra_defs = []
    if debug.get("trace_operation_delay", False):
        extra_defs.append("-DTRACE_OPERATION_DELAY")
    if debug.get("dump_ir_tensor_data", False):
        extra_defs.append("-DDEBUG_INTERMEDIATE")
    extra_defs_str = " ".join(extra_defs)

    makefile_content = f"""# Makefile for {model_name} - ncnn standalone
# Auto-generated by Sense Compiler

CXX = c++
ROOT_DIR := $(CURDIR)/../../..
INCLUDES = -I $(ROOT_DIR) -I $(ROOT_DIR)/include
CXXFLAGS = -O3 -Wall -std=c++17 -fPIC $(INCLUDES) {extra_defs_str}
LDFLAGS = -lm

TARGET = {model_name}

SRCS = lib/{model_name}.c lib/lib0.c
OBJS = lib/{model_name}.o lib/lib0.o

.PHONY: all clean debug debug-intermediate info help

all: $(TARGET)

$(TARGET): $(OBJS)
	@echo "Linking $@..."
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS)
	@echo "Build complete: $@"
	@ls -lh $@

lib/{model_name}.o: lib/{model_name}.c
	@echo "Compiling $<..."
	$(CXX) $(CXXFLAGS) -c -o $@ $<

lib/lib0.o: lib/lib0.c
	@echo "Compiling $<..."
	$(CXX) $(CXXFLAGS) -c -o $@ $<

clean:
	@echo "Cleaning..."
	rm -f $(OBJS) $(TARGET)
	@echo "Clean complete"

debug:
	$(MAKE) CXXFLAGS='-O0 -g -Wall -std=c++17 -fPIC $(INCLUDES) {extra_defs_str}' clean $(TARGET)

debug-intermediate:
	$(MAKE) CXXFLAGS='-O0 -g -DDEBUG_INTERMEDIATE -Wall -std=c++17 -fPIC $(INCLUDES) {extra_defs_str}' clean $(TARGET)

info:
	@echo "Build Configuration:"
	@echo "  Target: $(TARGET)"
	@echo "  Compiler: $(CXX)"
	@echo "  CXXFLAGS: $(CXXFLAGS)"
	@echo "  LDFLAGS: $(LDFLAGS)"

help:
	@echo "{model_name} - Makefile"
	@echo ""
	@echo "Targets:"
	@echo "  all                Build the executable (default)"
	@echo "  clean              Remove build artifacts"
	@echo "  debug              Build with debug symbols"
	@echo "  debug-intermediate Build with intermediate value debugging"
	@echo "  info               Show build configuration"
	@echo "  help               Display this help message"
"""

    makefile_path = output_dir / "Makefile"
    with open(makefile_path, "w") as f:
        f.write(makefile_content)

    return makefile_path
