"""Makefile generator for Sense compiled models"""
from pathlib import Path


def generate_makefile(output_dir: Path, model_name: str, debug: dict | None = None, **kwargs) -> Path:
    """Generate Makefile for building the compiled model

    Parameters
    ----------
        output_dir : Output directory where Makefile will be created
        model_name : Model name for the target executable

    Returns
    -------
        Path to the generated Makefile
    """
    debug = debug or {}
    extra_defs = []
    if debug.get("trace_operation_delay", False):
        extra_defs.append("-DTRACE_OPERATION_DELAY")
    if debug.get("dump_ir_tensor_data", False):
        extra_defs.append("-DDEBUG_INTERMEDIATE")
    extra_defs_str = " ".join(extra_defs)

    makefile_content = f"""# Makefile for {model_name} - Standalone (No TVM dependencies)
# Auto-generated by Sense Compiler

CC = gcc
CFLAGS = -O3 -Wall -fPIC {extra_defs_str}
LDFLAGS = -lm

# Main target
TARGET = {model_name}

# Source files (no TVM dependencies)
SRCS = lib/{model_name}.c lib/lib0.c
OBJS = lib/{model_name}.o lib/lib0.o

.PHONY: all clean test debug debug-intermediate info help

# Default target
all: $(TARGET)

# Link executable
$(TARGET): $(OBJS)
\t@echo "Linking $@..."
\t$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)
\t@echo "Build complete: $@"
\t@ls -lh $@

# Compile object files
lib/{model_name}.o: lib/{model_name}.c
\t@echo "Compiling $<..."
\t$(CC) $(CFLAGS) -c -o $@ $<

lib/lib0.o: lib/lib0.c
\t@echo "Compiling $<..."
\t$(CC) $(CFLAGS) -c -o $@ $<

# Clean
clean:
\t@echo "Cleaning..."
\trm -f $(OBJS) $(TARGET)
\trm -f test_input.bin test_output.bin
\t@echo "Clean complete"

# Test
test: $(TARGET)
\t@echo "Running test..."
\tpython3 -c "import numpy as np; np.random.seed(42); np.random.randn(1, 128, 192, 1).astype(np.float32).tofile('test_input.bin')"
\t./$(TARGET) test_input.bin test_output.bin
\t@echo "Test complete"

# Debug build
debug: CFLAGS = -O0 -g -Wall -fPIC
debug: clean $(TARGET)

# Debug intermediate values
debug-intermediate: CFLAGS = -O0 -g -DDEBUG_INTERMEDIATE -Wall -fPIC
debug-intermediate: clean $(TARGET)

# Info
info:
\t@echo "Build Configuration:"
\t@echo "  Target: $(TARGET)"
\t@echo "  Compiler: $(CC)"
\t@echo "  CFLAGS: $(CFLAGS)"
\t@echo "  LDFLAGS: $(LDFLAGS)"
\t@echo ""
\t@echo "Source Files:"
\t@echo "  $(SRCS)"
\t@echo ""
\t@echo "Object Files:"
\t@echo "  $(OBJS)"

# Help
help:
\t@echo "{model_name} - Makefile"
\t@echo ""
\t@echo "Targets:"
\t@echo "  all                Build the executable (default)"
\t@echo "  clean              Remove build artifacts"
\t@echo "  test               Run simple test"
\t@echo "  debug              Build with debug symbols"
\t@echo "  debug-intermediate Build with intermediate value debugging"
\t@echo "  info               Show build configuration"
\t@echo "  help               Display this help message"
"""

    makefile_path = output_dir / "Makefile"
    with open(makefile_path, 'w') as f:
        f.write(makefile_content)

    return makefile_path
